'use client';

import { useState, useRef, useLayoutEffect } from 'react';
import { ArrowUpRight, ArrowRight, Plus, Search, BookOpen, Link2, Sparkles, Leaf, Command, Check, FileText, MoveUpRight } from 'lucide-react';
import s from './designs.module.css';

const notes = [
  { title: 'A walk without a destination', category: 'Everyday observations', body: 'The best ideas arrive when there is room for them. Take the long way home. Notice what you usually pass.', tags: ['Attention', 'Creative practice'] },
  { title: 'Make space for the unfinished', category: 'Creative practice', body: 'A thought does not have to be complete to be worth keeping. Collect the fragments. The pattern comes later.', tags: ['First drafts', 'Attention'] },
  { title: 'The things we return to', category: 'Reading notes', body: 'What catches your attention twice deserves a place in your notebook. Repetition can be the beginning of a question.', tags: ['Attention', 'Reading'] },
];

function Mark({ name, kind = 'square' }: { name: string; kind?: string }) { return <a className={s.brand} href="#top"><span className={`${s.mark} ${s[kind] || ''}`} aria-hidden="true"><span /><span /><span /><span /></span>{name}</a>; }
function Start({ children = 'Try your first note', className = '', onClick }: { children?: React.ReactNode; className?: string; onClick?: () => void }) { return <a className={`${s.cta} ${className}`} href="#try" onClick={onClick}>{children}</a>; }
function Footer({ name }: { name: string }) { return <footer className={s.footer}>{name === "grove" ? <a className={s.brand} href="#top"><Leaf size={28} strokeWidth={1.5} />grove</a> : <Mark name={name} kind={name === "orbit" ? "round" : "square"} />}<a href="#top">Back to top ↑</a></footer>; }
function NoteCapture({ title = 'What’s on your mind?', compact = false, onSave }: { title?: string; compact?: boolean; onSave?: (value: string) => void }) {
  const [value, setValue] = useState(''); const [saved, setSaved] = useState<string[]>([]);
  return <form className={`${s.capture} ${compact ? s.compact : ''}`} onSubmit={e => { e.preventDefault(); if (value.trim()) { setSaved(v => [value.trim(), ...v]); onSave?.(value.trim()); setValue(''); } }}><label htmlFor="first-note">{title}</label><textarea id="first-note" value={value} onChange={e => setValue(e.target.value)} placeholder="An idea, a question, a sentence worth keeping…" rows={3} /><div className={s.captureBottom}><span>Interactive preview · saved for this visit</span><button type="submit" disabled={!value.trim()}>Keep this thought <Plus size={16} /></button></div><div role="status" className={s.saved}>{saved.length > 0 && <><Check size={15} /> Thought added to your notebook</>}</div>{saved.map((note, i) => <p className={s.savedNote} key={`${i}-${note}`}>{note}</p>)}</form>;
}

export function PageOne() {
  const [active, setActive] = useState(0);
  return <div className={`${s.page} ${s.margin}`} id="top"><a className={s.skip} href="#main">Skip to content</a><header className={s.header}><Mark name="margin" /><nav aria-label="Main"><a href="#how">The idea</a><a href="#try">Your notebook</a></nav><Start onClick={() => setActive(3)}>Make room</Start></header><main id="main"><section className={s.marginHero}><div className={s.marginCopy}><span className={s.eyebrow}>FOR THE THOUGHTS BETWEEN THINGS</span><h1>Your mind is<br />for making.<br /><em>Not holding.</em></h1><p>Give your ideas a place to land. Margin brings your notes, discoveries, and half-formed thoughts together—so you can see what comes next.</p><Start onClick={() => setActive(3)}>Open a little space</Start></div><div className={s.marginDesk} id="try"><div className={s.deskTop}><span><Command size={15} /> Your everyday notebook</span></div><div className={s.deskBody}><aside><span className={s.notebookLabel}>IN YOUR MARGIN</span>{notes.map((n, i) => <button key={n.title} onClick={() => setActive(i)} className={active === i ? s.activeNote : ''}><FileText size={15} /><span>{n.title}</span></button>)}<button className={active === 3 ? s.activeNote : ""} onClick={() => setActive(3)}><Plus size={15} />New thought</button></aside><div className={s.notebookCapture} hidden={active !== 3}><NoteCapture compact title="A new thought" /></div>{active !== 3 && <article className={s.openNote} key={active}><span className={s.noteMeta}>{notes[active].category}</span><h2>{notes[active].title}</h2><p>{notes[active].body}</p><blockquote>“Pay attention. Be astonished. Tell about it.”<small>A reminder for your next walk</small></blockquote><div className={s.tags}>{notes[active].tags.map(t => <span key={t}><Link2 size={12} />{t}</span>)}</div></article>}</div><div className={s.related}><span><Link2 size={15} /> A connection worth following</span><button onClick={() => setActive((active + 1) % 3)}>{notes[(active + 1) % 3].title}<ArrowUpRight size={16} /></button></div></div></section><section id="how" className={s.marginHow}><span className={s.sectionLabel}>LESS TO CARRY. MORE TO CONNECT.</span><h2>A note is a beginning,<br />not a dead end.</h2><p className={s.marginClosing}>Catch a small observation in your notebook. Follow its connections when you return. Your next idea can begin with a thought you already had.</p></section></main><Footer name="margin" /></div>;
}


function OrbitMap({ active, setActive, stars }: { active: number; setActive: (i: number) => void; stars: string[] }) {
  const graphRef = useRef<HTMLDivElement>(null);
  const [geometry, setGeometry] = useState<{ width: number; height: number; paths: string[] }>({ width: 1, height: 1, paths: [] });
  useLayoutEffect(() => {
    const graph = graphRef.current;
    if (!graph) return;
    const measure = () => {
      const bounds = graph.getBoundingClientRect();
      const core = graph.querySelector<HTMLElement>('[data-graph-core]')!.getBoundingClientRect();
      const center = { x: core.left + core.width / 2 - bounds.left, y: core.top + core.height / 2 - bounds.top };
      const paths = Array.from(graph.querySelectorAll<HTMLElement>('[data-graph-target]')).map(target => {
        const box = target.getBoundingClientRect();
        return `M${center.x} ${center.y} L${box.left + box.width / 2 - bounds.left} ${box.top + box.height / 2 - bounds.top}`;
      });
      setGeometry({ width: bounds.width, height: bounds.height, paths });
    };
    const observer = new ResizeObserver(measure);
    observer.observe(graph);
    graph.querySelectorAll<HTMLElement>('[data-graph-core], [data-graph-target]').forEach(node => observer.observe(node));
    window.addEventListener('resize', measure);
    let mounted = true;
    document.fonts.ready.then(() => { if (mounted) measure(); });
    measure();
    return () => { mounted = false; observer.disconnect(); window.removeEventListener('resize', measure); };
  }, []);
  return <div ref={graphRef} className={s.constellation} id="connections"><div className={s.orbitRing} /><div className={s.orbitRingInner} /><svg className={s.starLines} viewBox={`0 0 ${geometry.width} ${geometry.height}`} aria-hidden="true">{geometry.paths.map((d, i) => <path key={`${i}-${active === i}`} d={d} pathLength={1} className={active === i ? s.selectedPath : ''} />)}</svg><div className={s.starCore} data-graph-core><Sparkles size={26} /><span>YOUR SECOND BRAIN</span><strong key={active} className={s.orbitTopic}>{active === 3 ? 'Noticing' : notes[active].tags[0]}</strong></div>{stars.map((n, i) => <button data-graph-target className={`${s.starNote} ${s[`star${i}`]} ${active === i ? s.starSelected : ''}`} key={n} onClick={() => setActive(i)} aria-pressed={active === i}><span><FileText size={14} />{i === 0 ? 'READING' : i === 1 ? 'IDEAS' : 'QUESTIONS'}</span><strong>{n}</strong><small>{active === i ? 'Connected to the center' : 'Explore connection'} <ArrowUpRight size={12} /></small></button>)}<button className={`${s.starFragment} ${active === 3 ? s.fragmentSelected : ''}`} onClick={() => setActive(3)} aria-pressed={active === 3}><span className={s.starDot} data-graph-target />A walk without a destination</button></div>;
}

export function PageTwo() {
  const [active, setActive] = useState(0);
  const stars = ['The books I return to', 'Ways of paying attention', 'A question for tomorrow'];
  return <div className={`${s.page} ${s.orbit}`} id="top"><a className={s.skip} href="#main">Skip to content</a><header className={s.header}><Mark name="orbit" kind="round" /><nav aria-label="Main"><a href="#connections">Connections</a><a href="#try">Start exploring</a></nav><Start>Enter your orbit</Start></header><main id="main"><section className={s.orbitHero}><span className={s.eyebrow}>A SECOND BRAIN. A WIDER WORLD.</span><h1>Nothing you think<br />exists <em>alone.</em></h1><p>A home for your notes. A map of the connections between them.<br />Discover the bigger idea hiding in the small ones.</p><Start>Find your first connection</Start><OrbitMap active={active} setActive={setActive} stars={stars} /></section><section className={s.orbitExplain}><div><span className={s.sectionLabel}>FOLLOW YOUR CURIOSITY</span><h2>Your ideas have<br />more in common<br />than you think.</h2></div><div><p>Save the interesting thing. Link it to another. Over time, your notebook becomes a landscape you can explore.</p><ul><li><Plus />Collect without overthinking</li><li><Link2 />Connect across subjects</li><li><Search />Rediscover your own thinking</li></ul></div></section><section id="try" className={s.orbitTry}><span className={s.eyebrow}>EVERY ORBIT STARTS SOMEWHERE</span><h2>Put your first idea on the map.</h2><NoteCapture title="A thought worth connecting" /></section></main><Footer name="orbit" /></div>;
}

const collectionNotes = [notes[0], { title: 'A city with room for detours', category: 'Unfinished projects', body: 'Sketch a route that leaves room for curiosity. Follow the side street, mark the unexpected stop, and let the map stay unfinished.', tags: ['Creative practice', 'Walking'] }, { title: 'A passage worth returning to', category: 'Reading notes', body: 'Keep the image that stays with you after the book is closed. A landscape, a sentence, a new way to look at familiar things.', tags: ['Reading', 'Attention'] }];

export function PageThree() {
  const [selected, setSelected] = useState(1);
  return <div className={`${s.page} ${s.commonplace}`} id="top"><a className={s.skip} href="#main">Skip to content</a><header className={s.header}><Mark name="commonplace" /><nav aria-label="Main"><a href="#collection">The collection</a><a href="#try">Take a note</a></nav><a className={s.outlineAction} href="#try">Start collecting <Plus size={16} /></a></header><main id="main"><section className={s.commonHero}><div className={s.commonTitle}><span className={s.eyebrow}>YOUR PERSONAL COLLECTION OF EVERYTHING</span><h1>Keep what<br /><em>moves</em> you.</h1></div><div className={s.commonIntro}><p>Good ideas don’t arrive in order.<br />Commonplace gives them a home.</p><Start>Begin your collection</Start><span>Notes. Quotes. Questions. Possibilities.</span></div></section><section className={s.collection} id="collection"><div className={s.collectionHeading}><h2>A few things worth keeping.</h2><span>AN ILLUSTRATIVE COLLECTION / 001—003</span></div><div className={s.collectionGrid}>{collectionNotes.map((n, i) => <button className={`${s.collectionItem} ${selected === i ? s.collectionSelected : ''}`} key={n.title} onClick={() => setSelected(i)} aria-pressed={selected === i}><span className={s.collectionNumber}>00{i + 1}</span><div className={`${s.specimen} ${s[`artifact${i}`]}`} aria-hidden="true"><div className={s.artifactCrop} /></div><span className={s.collectionCategory}>{n.category}</span><h3>{n.title}</h3><span className={s.openCollection}>{selected === i ? 'Currently open' : 'Open this note'}<MoveUpRight size={20} /></span></button>)}</div><article className={s.collectionDetail} key={selected}><span>FROM THE COLLECTION</span><h2>{collectionNotes[selected].title}</h2><p>{collectionNotes[selected].body}</p><div className={s.tags}>{collectionNotes[selected].tags.map(t => <span key={t}>{t}</span>)}</div></article></section><section className={s.commonManifesto}><span className={s.sectionLabel}>A NOTEBOOK WITH NO WRONG TURNS</span><h2>Not everything needs<br />a folder. Sometimes<br />it just needs <em>a place.</em></h2><p>Collect freely. Give a thought a name, connect it to a theme, and return whenever curiosity calls. Your collection follows the way you think.</p></section><section id="try" className={s.commonTry}><h2>Add something of your own.</h2><NoteCapture title="Your collection starts here" /></section></main><Footer name="commonplace" /></div>;
}

export function PageFour() {
  const [grown, setGrown] = useState(false);
  const [seed, setSeed] = useState("Make time to notice.");
  return <div className={`${s.page} ${s.grove}`} id="top"><a className={s.skip} href="#main">Skip to content</a><header className={s.header}><a className={s.brand} href="#top"><Leaf size={28} strokeWidth={1.5} />grove</a><nav aria-label="Main"><a href="#grow">How ideas grow</a><a href="#try">Plant a thought</a></nav><Start>Your little grove</Start></header><main id="main"><section className={s.groveHero}><div className={s.groveIntro}><span className={s.eyebrow}>A QUIETER PLACE TO THINK</span><h1>Let your<br />ideas <em>grow.</em></h1><p>A second brain for the things you’re learning, making, and becoming. Give a small thought a little space. See what takes root.</p><Start>Plant your first thought</Start></div><div className={`${s.garden} ${grown ? s.gardenGrown : ""}`} id="grow"><svg className={s.gardenDrawing} viewBox="0 0 600 520" aria-hidden="true"><path d="M310 480 C280 330 340 285 300 90 M304 340 Q180 340 120 240 M310 255 Q435 255 480 160 M303 160 Q215 160 160 80" /><ellipse cx="230" cy="350" rx="58" ry="23" transform="rotate(25 230 350)" /><ellipse cx="375" cy="290" rx="61" ry="25" transform="rotate(-30 375 290)" /><ellipse cx="258" cy="192" rx="49" ry="21" transform="rotate(32 258 192)" /></svg><div className={s.seedCard} id="try"><button className={s.seedThought} onClick={() => setGrown(v => !v)} aria-expanded={grown}><span>THE SEED</span><h2 key={seed}>{seed}</h2><span><Link2 size={13} />{grown ? "Fold related thought" : "See what connects"}</span></button><NoteCapture compact title="Plant a thought" onSave={setSeed} /></div><button className={s.branchCard} onClick={() => setGrown(v => !v)} aria-expanded={grown}><span><BookOpen size={14} /> Reading note</span><strong>The art of paying attention</strong></button><button className={s.growButton} onClick={() => setGrown(!grown)} aria-expanded={grown}><Plus size={17} />{grown ? 'Fold this connection' : 'Grow a connection'}</button><div className={s.growingLeaf} aria-hidden={!grown}><div><div className={s.newLeaf}><Link2 size={15} /><strong>A walk without a destination</strong><p>Another way to make room for noticing.</p></div></div></div><span className={s.growthStatus} role="status">{grown ? "Related thought revealed" : ""}</span></div></section></main><Footer name="grove" /></div>;
}

export function PageFive() {
  const [step, setStep] = useState(0);
  const steps = ['Catch it', 'Connect it', 'Make something'];
  return <div className={`${s.page} ${s.relay}`} id="top"><a className={s.skip} href="#main">Skip to content</a><header className={s.header}><Mark name="relay" /><nav aria-label="Main"><a href="#flow">The flow</a><a href="#try">Try it out</a></nav><Start>Get thinking</Start></header><main id="main"><section className={s.relayHero}><div className={s.relayHeadline}><span className={s.eyebrow}>THOUGHTS IN. POSSIBILITIES OUT.</span><h1>From “what if”<br />to <span>what’s next.</span><ArrowUpRight aria-hidden="true" /></h1></div><div className={s.relaySub}><p>Your notes should take you somewhere. Relay turns scattered thinking into connected ideas you can actually use.</p><Start>Take an idea for a spin</Start></div></section><section className={s.flow} id="flow"><div className={`${s.flowTabs} ${s[`tabStep${step}`]}`} aria-label="Explore the note workflow">{steps.map((title, i) => <button key={title} onClick={() => setStep(i)} aria-pressed={step === i} className={step === i ? s.flowActive : ''}><span>0{i + 1}</span>{title}<ArrowRight size={18} /></button>)}</div><div className={s.flowStage}><div className={s.flowContext} key={step}><span>{['ANYWHERE AN IDEA HAPPENS', 'ONE THOUGHT MEETS ANOTHER', 'YOUR THINKING, IN MOTION'][step]}</span><h2>{[<>Don’t let<br />it get away.</>, <>Find your<br />throughline.</>, <>Give an idea<br />a next step.</>][step]}</h2><p>{['A quick note beats a perfect memory.', 'Related notes make more sense together.', 'Turn your collection into a starting point.'][step]}</p></div><div className={`${s.relayObjects} ${s[`relayStep${step}`]}`}><article className={s.relayObjectOne}><span><FileText size={14} />A QUESTION</span><h3>What if the best part of a project is the question it starts with?</h3><p>#making &nbsp; #questions</p></article><div className={s.relayThread}><Link2 size={18} /><span>Creative practice</span></div><article className={s.relayObjectTwo}><span><FileText size={14} />AN OBSERVATION</span><h3>Leave room for a detour.</h3><p>#creative-practice</p></article><article className={s.relayOutcome} aria-hidden={step !== 2}><span><Sparkles size={14} />A NEW DIRECTION</span><h3>A project about taking the long way.</h3><p>Start with a walk. Collect three things you notice. Let the questions shape the work.</p><span><Check size={14} />Connected to both notes</span></article></div></div><p className={s.flowHint}>Select a step to explore the example.</p></section><section className={s.relayBottom}><h2>A second brain.<br /><span>A first step.</span></h2><p>Keep the raw material. Connect the dots.<br />Make space for the work only you can do.</p></section><section id="try" className={s.relayTry}><NoteCapture title="Catch your next idea" /></section></main><Footer name="relay" /></div>;
}
