import Image from "next/image";
import { Geist, Space_Grotesk, Manrope } from "next/font/google";
import { ArrowUpRight, ArrowRight, BookmarkSimple, Brain, Stack, LinkSimple, Feather, Asterisk, CircleHalf, ArrowBendUpRight, Notebook, Tree, CursorText } from "@phosphor-icons/react/dist/ssr";
import writingImage from "./assets/writing.png";
import forestImage from "./assets/forest.png";
import lakeImage from "./assets/lake.png";
import { Reveal } from "./MotionLeaf";
import { NoteDemo } from "./NoteDemo";
import s from "./designs.module.css";

const geist=Geist({subsets:["latin"],display:"swap"});
const space=Space_Grotesk({subsets:["latin"],display:"swap"});
const manrope=Manrope({subsets:["latin"],display:"swap"});
const photo=(id:number)=>id===28?forestImage:id===29?lakeImage:writingImage;
function Photo({id,alt,hero=false,className=""}:{id:number;alt:string;hero?:boolean;className?:string}){return <div className={`${s.photo} ${className}`}><Image src={photo(id)} alt={alt} fill sizes="(max-width: 767px) 100vw, 55vw" priority={hero} /></div>}
function Nav({brand,mark="stack"}:{brand:string;mark?:string}){return <header className={s.nav}><a href="#" className={s.brand}>{mark==="feather"?<Feather weight="fill" />:mark==="star"?<Asterisk weight="bold" />:mark==="brain"?<Brain weight="regular" />:mark==="circle"?<CircleHalf weight="fill" />:<Stack weight="fill" />}{brand}</a><nav aria-label="Main navigation"><a href="#ideas">Why {brand}</a><a href="#how">How it works</a><a href="#try" className={s.navCta}>Try the notebook <ArrowUpRight size={16} /></a></nav></header>}
function CTA(){return <a className={s.button} href="#try">Try the notebook <ArrowUpRight size={19} /></a>}
function Footer({brand}:{brand:string}){return <footer className={s.footer}><a className={s.brand} href="#">{brand}</a><p>A home for everything on your mind.</p><a href="#how">Explore the idea <ArrowUpRight size={16}/></a></footer>}

export function PageOne(){return <main className={`${s.page} ${s.one} ${geist.className}`}><div className={s.container}><Nav brand="goodkeep" />
  <section className={s.heroOne}><Reveal className={s.copy}><span className={s.eyebrow}>Make room for your mind</span><h1>Keep the thought.<br/>Find the thread.</h1><p>Capture what matters. Connect your ideas. Build a second brain that feels like yours.</p><div className={s.actions}><CTA/><a className={s.textLink} href="#how">Take a closer look <ArrowRight size={18}/></a></div></Reveal><Reveal className={s.oneImage} delay={.12}><Photo id={28} alt="Sunlight threading through a green forest" hero/></Reveal></section>
  <section id="ideas" className={s.keepSection}><h2>Your mind makes connections.<br/>Your notes should, too.</h2><div className={s.keepGrid}><div><LinkSimple size={32}/><h3>Ideas belong together.</h3><p>A sentence from a book. A thought on a walk. Keep the connections, not just the files.</p></div><Photo id={29} alt="Quiet lakeside landscape"/><div><BookmarkSimple size={32}/><h3>Less searching.<br/>More finding.</h3><p>Bring the right thought back when you need it, without remembering where you put it.</p></div></div></section>
  <Reveal><section id="how" className={s.simpleProcess}><h2>From passing thought<br/>to something worth making.</h2><div><p><strong>Catch it</strong>Write it before it disappears.</p><p><strong>Connect it</strong>Link a note to another idea.</p><p><strong>Come back</strong>Pick up the thread whenever you are ready.</p></div></section></Reveal><Photo id={180} alt="A quiet workspace for writing" className={s.bannerPhoto}/><NoteDemo brand="goodkeep"/><Footer brand="goodkeep"/></div></main>}

export function PageTwo(){return <main className={`${s.page} ${s.two} ${manrope.className}`}><div className={s.container}><Nav brand="Commonplace" mark="feather"/>
  <section className={s.heroTwo}><Reveal className={s.copy}><h1>A place for<br/>your whole mind.</h1><p>Notes, discoveries, and half-formed ideas. Together in a space that grows with you.</p><div className={s.actions}><CTA/></div></Reveal><Reveal className={s.twoImages} delay={.14}><Photo id={24} alt="A book kept open for a quiet moment" hero/><Photo id={29} alt="Still water reflecting a distant landscape"/></Reveal></section>
  <section id="ideas" className={s.editorialSection}><div className={s.editorialTitle}><h2>You do not think<br/>in folders.</h2><p>Let one idea lead to another. A personal collection becomes a living source of inspiration.</p></div><Reveal className={s.editorialColumns}><Photo id={28} alt="Sunlight finding its way through a woodland"/><div className={s.essay}><Feather size={30}/><h3>Start with a sentence.</h3><p>You do not need a system to begin. Save a quote, write a question, or capture a moment.</p><h3>Leave a trail.</h3><p>Link related thoughts so your next visit starts with something familiar.</p></div></Reveal></section>
  <section id="how" className={s.bigStatement}><span>Collect. Connect. Revisit.</span><h2>A notebook today.<br/>A way of thinking tomorrow.</h2><p>Keep adding a little. Your knowledge takes shape over time.</p></section><NoteDemo brand="Commonplace"/><Footer brand="Commonplace"/></div></main>}

export function PageThree(){return <main className={`${s.page} ${s.three} ${space.className}`}><div className={s.container}><Nav brand="recall" mark="brain"/>
  <section className={s.heroThree}><Reveal className={s.copy}><span className={s.eyebrow}>For the curious mind</span><h1>Remember more.<br/>Think further.</h1><p>Turn scattered notes into connected knowledge. Your second brain starts with one idea.</p><div className={s.actions}><CTA/><a href="#ideas" className={s.textLink}>See the difference <ArrowRight size={18}/></a></div></Reveal><Reveal className={s.threeVisual} delay={.12}><Photo id={0} alt="Laptop on a desk, ready to capture an idea" hero/><div className={s.visualCaption}><Brain size={26}/><p>One place to build on<br/>everything you know.</p></div></Reveal></section>
  <section id="ideas" className={s.recallFeatures}><h2>The thought is only the beginning.</h2><div className={s.recallGrid}><article><Notebook size={34}/><h3>Capture without friction.</h3><p>Write now. Organize when your thoughts have had time to settle.</p><Photo id={28} alt="A green woodland path in natural light"/></article><article><LinkSimple size={34}/><h3>Follow the connection.</h3><p>A related thought is often the missing piece. Link notes and see what comes together.</p><Photo id={29} alt="A wide landscape with water and trees"/></article></div></section>
  <Reveal><section id="how" className={s.workflow}><h2>Build your thinking habit.</h2><div><article><CursorText size={25}/><h3>Write a thought</h3><p>Meet the blank page with a sentence.</p></article><ArrowRight size={24}/><article><LinkSimple size={25}/><h3>Make a connection</h3><p>Bring it into your growing collection.</p></article><ArrowRight size={24}/><article><Brain size={25}/><h3>Return with context</h3><p>Find an idea worth building on.</p></article></div></section></Reveal><NoteDemo brand="recall"/><Footer brand="recall"/></div></main>}

export function PageFour(){return <main className={`${s.page} ${s.four} ${space.className}`}><div className={s.container}><Nav brand="offscript" mark="star"/>
  <section className={s.heroFour}><Reveal className={s.copy}><h1>Messy thoughts.<br/>Good company.</h1><p>Your ideas do not arrive in order. Give every spark a home, and see what happens next.</p><div className={s.actions}><CTA/></div></Reveal><Reveal className={s.fourVisual} delay={.1}><Photo id={180} alt="An everyday desk with room to work and create" hero/></Reveal></section>
  <section id="ideas" className={s.offscriptIntro}><Asterisk size={62} weight="bold"/><h2>A second brain.<br/>With room to wander.</h2><p>For the tangent that becomes a project. The question that becomes a plan. And everything you have not figured out yet.</p></section>
  <Reveal><section className={s.offscriptTiles}><article><Photo id={28} alt="A green woodland path"/><h3>Keep your curiosity.</h3><p>Collect what catches your attention, even before you know why.</p></article><article><LinkSimple size={54}/><h3>Pull on a thread.</h3><p>Find the surprising connection between yesterday’s note and today’s idea.</p></article><article><Photo id={29} alt="A peaceful lake opening toward the mountains"/><h3>Make it yours.</h3><p>Build a collection that follows your interests, at your pace.</p></article></section></Reveal>
  <section id="how" className={s.offscriptHow}><h2>No perfect system required.</h2><details open><summary>Start small <ArrowBendUpRight size={24}/></summary><p>Write one thing you want to remember. That is enough to begin.</p></details><details><summary>Add a connection <ArrowBendUpRight size={24}/></summary><p>Notice a related idea? Give it a link. Keep thinking out loud.</p></details><details><summary>See where it goes <ArrowBendUpRight size={24}/></summary><p>Return to your notes and follow a thought into your next project.</p></details></section><NoteDemo brand="offscript"/><Footer brand="offscript"/></div></main>}

export function PageFive(){return <main className={`${s.page} ${s.five} ${manrope.className}`}><div className={s.container}><Nav brand="thread" mark="circle"/>
  <section className={s.heroFive}><Reveal className={s.copy}><span className={s.eyebrow}>A little clarity, every day</span><h1>Let your mind<br/>make room.</h1><p>Keep your ideas somewhere you trust. Find the connections that help you move forward.</p><div className={s.actions}><CTA/><a href="#how" className={s.textLink}>How it feels <ArrowRight size={18}/></a></div></Reveal><Reveal className={s.fiveVisual} delay={.15}><Photo id={29} alt="A peaceful lake and wooded shore" hero/></Reveal></section>
  <section id="ideas" className={s.threadIntro}><h2>Less in your head.<br/>More at your fingertips.</h2><p>A thought can wait without getting lost. Thread holds the things you want to come back to.</p><Reveal className={s.threadPair}><Photo id={28} alt="Sunlight falling through a forest"/><div><Tree size={34}/><h3>Knowledge grows<br/>from small beginnings.</h3><p>A saved sentence. A fresh question. A connection you did not see before.</p></div><Photo id={180} alt="A place to sit and write"/></Reveal></section>
  <section id="how" className={s.threadHow}><div><h2>Meet your mind<br/>where it is.</h2><p>No elaborate setup. No need to have the answer. Just space to think.</p></div><div><article><BookmarkSimple size={28}/><h3>Keep what matters</h3><p>Catch the thought while it is here.</p></article><article><LinkSimple size={28}/><h3>See what connects</h3><p>Bring related ideas closer together.</p></article><article><ArrowBendUpRight size={28}/><h3>Pick it up again</h3><p>Keep the context for your next visit.</p></article></div></section><NoteDemo brand="thread"/><Footer brand="thread"/></div></main>}
