"use client";

import { useRef, useState } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, BookOpen, Check, Link2, Plus, Quote, RotateCcw, ScanLine, Search } from "lucide-react";
import s from "./iteration-two.module.css";

const trails = [
  { name: "Creative work", question: "What makes a good idea possible?", title: "Ideas need somewhere to meet.", excerpt: "Creativity is the ability to connect experiences and synthesize new things.", source: "Reading note · On creative practice", connection: "A good idea isn’t always a new thought. Sometimes it’s a new relationship between thoughts you already have.", tags: ["Attention", "Creative practice", "Unexpected connections"] },
  { name: "Learning", question: "How do I make learning stick?", title: "Return, don’t just repeat.", excerpt: "Recall something before you look it up. The effort of remembering is part of the learning.", source: "Study note · Retrieval practice", connection: "A question is often a better bookmark than a highlight. It gives future-you a reason to come back.", tags: ["Memory", "Practice", "Questions"] },
  { name: "Everyday life", question: "Where does my attention go?", title: "Keep a record of what matters.", excerpt: "The small things we attend to become the stories we tell about our lives.", source: "Journal note · A quiet Tuesday", connection: "Keeping a note is a way of choosing what deserves your attention again.", tags: ["Observation", "Journaling", "Attention"] },
];

export function PageTwo() {
  const [trail, setTrail] = useState(0);
  const [linked, setLinked] = useState(false);
  const [custom, setCustom] = useState("");
  const [saved, setSaved] = useState<{body:string; trail:string}[]>([]);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("Choose a trail, read the fragment, and connect the idea.");
  const input = useRef<HTMLTextAreaElement>(null);
  const active = trails[trail];
  function start() { document.getElementById("thread-workbench")?.scrollIntoView({ behavior: "instant", block: "start" }); input.current?.focus({preventScroll:true}); }
  function connect() { setLinked(!linked); setStatus(linked ? "Connection removed. Your source note is still here." : "Connected. The original source now leads to your own idea."); }
  function save() { if (!custom.trim()) {setStatus("Add your own thought before saving it."); input.current?.focus(); return;} setSaved([...saved,{body:custom.trim(),trail:active.name}]); setCustom(""); setStatus(`Your thought is saved in this page session and linked to ${active.name}.`); }
  function choose(index:number) {setTrail(index);setLinked(false);setStatus(`Opened ${trails[index].name}. Connect the fragment to see the next idea.`);}
  return <main className={s.page}>
    <a className={s.skip} href="#thread-workbench">Skip to the interactive workbench</a>
    <header className={s.header}><a href="#thread-top" className={s.brand}><span aria-hidden="true">↳</span> thread</a><nav aria-label="Thread navigation"><a href="#thread-method">The method</a><a href="#thread-workbench">Explore a trail</a></nav><button className={s.navAction} onClick={start}>Open your mind <ArrowUpRight size={17}/></button></header>
    <section className={s.hero} id="thread-top"><div className={s.heroTop}><span className={s.label}><span className={s.signal}/> NOTES THAT GO SOMEWHERE</span><span className={s.serial}>A SECOND BRAIN / AN OPEN END</span></div><h1>Follow a thought.<br/><span>Find your next one.</span></h1><div className={s.heroBottom}><p>Not another pile of saved things.<br/>A place to turn what you collect into<br/>what you think, make, and do.</p><button className={s.bigAction} onClick={start}>Pull the thread <ArrowDown size={23}/></button><div className={s.miniTrail} aria-hidden="true"><span>Read</span><i/><span>Remember</span><i/><span>Reimagine</span></div></div></section>
    <section className={s.workbenchSection} id="thread-workbench"><div className={s.workbenchIntro}><p>TRY A LITTLE CONNECTED THINKING</p><span>Illustrative notes · changes stay in this session</span></div><div className={s.workbench}>
      <aside className={s.trails}><span className={s.trailLabel}><ScanLine size={17}/> YOUR TRAILS</span>{trails.map((t,index)=><button key={t.name} onClick={()=>choose(index)} aria-pressed={trail===index} className={trail===index?s.activeTrail:""}><span>0{index+1}</span>{t.name}<ArrowUpRight size={15}/></button>)}<div className={s.trailThought}><span>A QUESTION TO CARRY</span><p>{active.question}</p></div><label className={s.search}><Search size={15}/><span className={s.srOnly}>Search your saved thoughts</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find your saved thoughts"/></label><span className={s.savedLabel}>{saved.length} personal {saved.length===1?"thought":"thoughts"}</span>{saved.length===0?<p className={s.empty}>Your next thought belongs here.</p>:<ul className={s.savedList}>{saved.filter(n=>`${n.body} ${n.trail}`.toLowerCase().includes(search.toLowerCase())).map((note,index)=><li key={index}><span className={s.savedTrail}>{note.trail}</span>{note.body}</li>)}</ul>}{saved.length>0 && !saved.some(n=>`${n.body} ${n.trail}`.toLowerCase().includes(search.toLowerCase())) && <p className={s.empty}>No matches. Try a different word.</p>}</aside>
      <div className={s.source}><div className={s.documentHead}><BookOpen size={18}/><span>THE THING YOU FOUND</span><span>01</span></div><h2>{active.title}</h2><blockquote><Quote size={21}/><p>{active.excerpt}</p></blockquote><p className={s.sourceAttribution}>{active.source}</p><div className={s.tags}>{active.tags.map(tag=><span key={tag}>{tag}</span>)}</div><button className={`${s.connect} ${linked?s.isConnected:""}`} onClick={connect}><Link2 size={18}/>{linked?"Connected to your thinking":"Connect this thought"}<span className={s.plus} aria-hidden="true"><i/><i style={{transform:linked?"scaleY(0)":"scaleY(1)"}}/></span></button><span className={s.smallLabel}>A source is a starting point. Your thinking is the next step.</span></div>
      <div className={s.thinking}><div className={s.documentHead}><span className={s.connectionMark} aria-hidden="true">↳</span><span>THE THING YOU MAKE</span><span>02</span></div><div className={`${s.idea} ${linked?s.ideaRevealed:""}`}><p className={s.ideaEyebrow}>{linked?"A connection worth keeping":"Room for a connection"}</p><h3>{linked?"That reminds me…":"What does this connect to?"}</h3><p>{linked?active.connection:"Pull a thread from the source. An observation, an old note, an idea for what comes next."}</p><div className={s.connectionPath}><span>{active.name}</span><ArrowRight size={16}/><span>{linked?"Your new perspective":"An open possibility"}</span></div></div><div className={s.capture}><label htmlFor="thread-note">Add your own next thought</label><textarea ref={input} id="thread-note" value={custom} onChange={e=>setCustom(e.target.value)} placeholder="This makes me think about…" rows={3} maxLength={800}/><button onClick={save}>Save to this trail <Plus size={17}/></button></div></div>
    </div><div className={s.workbenchFooter}><p role="status"><Check size={14}/>{status}</p><button onClick={()=>{setLinked(false);setCustom("");setSaved([]);setSearch("");setStatus("Sample reset. Pick a thread and begin again.");}}><RotateCcw size={14}/> Reset sample</button></div></section>
    <section className={s.method} id="thread-method"><div className={s.methodHeading}><span className={s.label}>FROM STORAGE TO SOMETHING MORE</span><h2>A note is a beginning.<br/><em>Not a dead end.</em></h2></div><div className={s.methodRows}><article><span>01</span><div><h3>Keep the source.</h3><p>A sentence from a book. A link you want to revisit. The detail that caught your attention.</p></div><BookOpen size={28} strokeWidth={1}/></article><article><span>02</span><div><h3>Make the connection.</h3><p>Put an old thought next to a new one. Keep the context, and follow what they have in common.</p></div><Link2 size={28} strokeWidth={1}/></article><article><span>03</span><div><h3>Find your own words.</h3><p>Collecting is only half the story. Turn a fragment into a point of view you can return to.</p></div><Quote size={28} strokeWidth={1}/></article></div></section>
    <section className={s.closing}><span className={s.endmark} aria-hidden="true">↳</span><div><p>YOUR MIND IS ALREADY MAKING CONNECTIONS.</p><h2>Give them<br/>somewhere to go.</h2><button onClick={start}>Start a thread <ArrowUpRight size={23}/></button></div></section><footer className={s.footer}><a href="#thread-top" className={s.brand}><span aria-hidden="true">↳</span> thread</a><span>Keep a thought. Change your mind.</span><a href="#thread-top">Back to top ↑</a></footer>
  </main>;
}
