"use client";
/* Hallmark · pre-emit critique: P4 H4 E4 S4 R4 V5 */
import { useState, type ReactNode } from "react";
import s from "./designs.module.css";

function Mark({small=false}:{small?:boolean}) { return <span className={small?s.smallMark:s.mark} aria-label="Commonplace">c<span aria-hidden="true">✳</span></span>; }
function LetterForm(){const [text,setText]=useState("");const [saved,setSaved]=useState(false);return <form className={s.letterForm} onSubmit={e=>{e.preventDefault();setSaved(true)}}><label htmlFor="hallmark-return-thought">A thought to return to</label><div><input id="hallmark-return-thought" value={text} required placeholder="Remember to…" onChange={e=>{setText(e.target.value);setSaved(false)}}/><button className={s.button} disabled={saved}>{saved?"✓ Kept":"Keep it →"}</button></div><p className={s.helper} role="status">{saved?"Kept in this local demo.":"A private draft on this page."}</p></form>}
function Capture({id}:{id:string}) {
  const [note,setNote]=useState(""); const [saved,setSaved]=useState(false);
  return <section id={id} className={s.capture}><h2>Give that thought a home.</h2><label htmlFor={`${id}-note`}>Your first note</label><textarea id={`${id}-note`} value={note} placeholder="Something worth remembering…" onChange={e=>{setNote(e.target.value);setSaved(false)}}/><button disabled={!note.trim() || saved} onClick={()=>setSaved(true)} className={s.button}>{saved?"✓ Note saved":"Save this thought →"}</button><p className={s.helper} role="status">{saved?"Saved in this page’s local demo. Your words are right here.":"Try a note. Nothing leaves this page."}</p></section>;
}
function Note({title,children,kind="Field note"}:{title:string;children:ReactNode;kind?:string}) { return <article className={s.note}><p className={s.noteKind}>{kind}</p><h3>{title}</h3><div>{children}</div></article>; }
const samples=[{title:"A place to begin",category:"Ideas",body:"The best ideas arrive before you have a place to put them. Leave a little room for the unfinished."},{title:"Paying attention",category:"Reading",body:"Keep the sentence that made you stop. Write why it mattered. Connect it to something you already know."},{title:"Walking notebook",category:"Everyday",body:"A different route home. The name of a tree. A question to return to. Small things are still worth keeping."},{title:"Before the project",category:"Ideas",body:"A collection of fragments: a reference, a sketch, a conversation. Give them time to find each other."}];

export function PageOne() {const [selected,setSelected]=useState(0);return <main data-hallmark-theme="garden" className={`${s.page} ${s.garden}`}>
  <header className={s.mast}><p>A notebook for the things you notice</p><a href="#garden-tour" className={s.mastName}>Commonplace</a><nav aria-label="Primary"><a href="#garden-tour">The notebook</a><a href="#garden-capture">Write a note</a></nav></header>
  <section id="garden-tour" className={s.workHero}><div><h1>Keep a thought.<br/>Grow an idea.</h1><p>Notes, links, loose ends. A place to collect them—and find the thread between them.</p></div><p className={s.aside}>Your second brain,<br/>with room to wander.</p></section>
  <section className={s.workbench}><div className={s.demoTop}><span>Inside your commonplace</span><span>Interactive notebook demo</span></div><div className={s.notebook}><nav aria-label="Example notes" className={s.noteList}><span className={s.listTitle}>Open a thought</span>{samples.map((x,i)=><button key={x.title} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{x.title}<span>↗</span></button>)}<a href="#garden-capture">+ Add your own</a></nav><div className={s.noteContent} key={selected}><Note title={samples[selected].title} kind={samples[selected].category}><p>{samples[selected].body}</p><a href="#garden-capture">Keep this thread going →</a></Note><div className={s.related}><span>Connected thought</span><p>{samples[(selected+1)%samples.length].title} ↗</p></div></div></div><p className={s.caption}>Start anywhere. Your ideas don’t have to arrive in order.</p></section>
  <section className={s.gardenLower}><div><h2>A collection that becomes a conversation.</h2><p>Capture first. Make connections later. Revisit an old note and find a new direction.</p></div><div className={s.process}><p><b>Collect</b><span>A sentence, a link, a passing thought.</span></p><p><b>Connect</b><span>Let one note point to another.</span></p><p><b>Return</b><span>Pick up a thread when you need it.</span></p></div></section><Capture id="garden-capture"/><footer className={s.footerMast}><Mark/><p>For a life worth noticing.</p><a href="#garden-tour">Back to notebook ↑</a></footer>
</main>}

export function PageTwo(){return <main data-hallmark-theme="manifesto" className={`${s.page} ${s.manifesto}`}><header className={s.edge}><a href="#manifesto-start"><Mark small/></a><a className={s.link} href="#manifesto-write">Write something ↗</a></header><section id="manifesto-start" className={s.poster}><div className={s.posterMark} aria-hidden="true">✳</div><h1>YOUR MIND.<br/>MORE ROOM.</h1><p className={s.posterFoot}>Commonplace / A second brain for your first thoughts.</p></section><section className={s.claim}><p>You don’t need another feed.</p><h2>You need somewhere<br/>to put it all.</h2><p>The half-formed idea. The line you underlined. The question that follows you home.</p></section><section className={s.manifestoTools}><h2>KEEP.<br/>LINK.<br/>COME BACK.</h2><div><p><b>Keep what catches you.</b><br/>Write a note before the thought disappears.</p><p><b>Follow your own connections.</b><br/>Link a reading note to an idea in progress.</p><p><b>Find a way back.</b><br/>Browse the fragments until a pattern appears.</p><a className={s.button} href="#manifesto-write">Make room →</a></div></section><Capture id="manifesto-write"/><footer className={s.footerLine}>Commonplace · Your thoughts belong to you. <a href="#manifesto-start">Return ↑</a></footer></main>}

export function PageThree(){return <main data-hallmark-theme="atelier" className={`${s.page} ${s.atelier}`}><nav className={s.minNav} aria-label="Primary"><a href="#letter-start">Commonplace</a><div><a href="#letter-read">Read the letter</a><a href="#letter-write">Write a note</a></div></nav><article id="letter-start" className={s.letter}><p className={s.salutation}>A note to the note-taker,</p><h1>Some thoughts<br/>deserve to stay.</h1><p className={s.letterLead}>A book leaves a sentence in your head. A conversation opens a question. Somewhere between one thing and the next, an idea appears.</p><p>You tell yourself you’ll remember it. Then the day moves on.</p><div className={s.letterRule} aria-hidden="true">✳</div><div id="letter-read"><h2>A commonplace, of your own.</h2><p>Commonplace is a note-taking application built around a simple idea: your mind should have somewhere to set things down.</p><p>Keep a fragment without deciding what it means. Gather your reading beside your projects. Add a connection when one occurs to you. An unfinished thought is welcome here.</p><blockquote>Not every note needs a purpose.<br/>Some just need a place.</blockquote><h2>The useful part is returning.</h2><p>A second brain isn’t a warehouse. It’s a conversation with the person you were when you wrote something down. Search a phrase. Follow a link. Find the question you forgot you were asking.</p><p>And when you find it, <a className={s.link} href="#letter-write">write the next thought ↗</a>.</p></div></article><div className={s.letterCapture}><Capture id="letter-write"/></div><footer className={s.letterClose}><p>Keep in touch with yourself,<br/><span>Commonplace</span></p><p>Leave a little room for what comes next.</p></footer></main>}

export function PageFour(){const [open,setOpen]=useState(0);const questions=[{q:"What is a second brain?",a:"Somewhere to keep what your mind is already carrying. Notes from your reading, fragments of ideas, references for a project. A place you can return to when you need a thread."},{q:"Where do I start?",a:"With a single note. There’s no taxonomy to learn before you write. Give the thought a title, put it down, and let the structure follow."},{q:"How do notes connect?",a:"A note can point to another note. A reading fragment becomes part of a project. A small observation finds its way into a larger idea."},{q:"Must I organise it?",a:"No. A loose fragment is still a useful note. Start with the thought itself; make a collection when there’s something worth gathering."},{q:"Can I try it?",a:"Yes. The note field below is a local demonstration. You can type and save a thought on this page. It won’t send your note anywhere."}];return <main data-hallmark-theme="almanac" className={`${s.page} ${s.almanac}`}><nav className={s.rail} aria-label="Page sections"><a href="#questions-start">COMMONPLACE</a><div><a href="#questions">Questions</a><a href="#questions-write">Try a note</a></div><span>Notes on note-taking</span></nav><div className={s.faqBody}><header id="questions-start" className={s.faqIntro}><p>Commonplace, explained.</p><h1>A second brain.<br/>A few first questions.</h1><p>You bring the thoughts.<br/>Here’s what happens next.</p></header><section id="questions" className={s.faq}>{questions.map((x,i)=><div className={s.faqRow} key={x.q}><h2><button aria-expanded={open===i} aria-controls={`hallmark-answer-${i}`} onClick={()=>setOpen(open===i?-1:i)}><span>{x.q}</span><span aria-hidden="true">{open===i?"−":"+"}</span></button></h2><div hidden={open!==i} id={`hallmark-answer-${i}`} className={s.answer}><p>{x.a}</p></div></div>)}</section><Capture id="questions-write"/><footer className={s.colophon}><b>COMMONPLACE</b><p>A small working demonstration of a personal knowledge notebook. Built around capture, connection, and return. No account required for the note on this page.</p><a href="#questions-start">Back to the first question ↑</a></footer></div></main>}

export function PageFive(){const [filter,setFilter]=useState("All");const [active,setActive]=useState<number|null>(null);const [banner,setBanner]=useState(true);return <main data-hallmark-theme="newsprint" className={`${s.page} ${s.newsprint}`}><header className={s.indexNav}>{banner&&<div className={s.banner}><span>Start a collection. Subscribe to your own train of thought.</span><button aria-label="Dismiss introduction" onClick={()=>setBanner(false)}>×</button></div>}<div className={s.indexBar}><a href="#index-top">Commonplace</a><a href="#index-write">Add a thought +</a></div></header><div className={s.indexBody}><header id="index-top" className={s.indexIntro}><div><h1>An index of<br/>things worth keeping.</h1><p>Read a fragment. Follow a connection.<br/>Leave one of your own.</p></div><span className={s.indexOrnament} aria-hidden="true">✳</span></header><div className={s.filter} role="group" aria-label="Filter example notes">{["All","Ideas","Reading","Everyday"].map(x=><button key={x} aria-pressed={filter===x} onClick={()=>{setFilter(x);setActive(null)}}>{x}</button>)}</div><section className={s.indexList} aria-label="Sample collection">{samples.map((x,i)=>(filter==="All"||filter===x.category)&&<article key={x.title}><button aria-expanded={active===i} onClick={()=>setActive(active===i?null:i)}><span className={s.indexCategory}>{x.category}</span><span className={s.indexTitle}>{x.title}</span><span aria-hidden="true">{active===i?"−":"↗"}</span></button>{active===i&&<div className={s.indexExcerpt}><p>{x.body}</p><a href="#index-write">Add a connected thought →</a></div>}</article>)}</section><p className={s.indexExplain}>Sample notes, ready to explore. The next entry could be yours.</p><Capture id="index-write"/><footer className={s.subscribe}><h2>A letter to your future self.</h2><p>Your notebook is a publication for an audience of one. Keep a thought below to begin your next entry.</p><LetterForm/><div><span>Commonplace</span><a href="#index-top">Back to the index ↑</a></div></footer></div></main>}


