"use client";

import { useId, useRef, useState, type ReactNode } from "react";
import { ArrowUpRight, ArrowRight, Plus, Search, Network, FileText, Leaf, Check, CornerDownLeft, Link2, Bookmark, Menu, X, Command, Layers, MoveUpRight, Circle } from "lucide-react";
import s from "./designs.module.css";

function Start({ children = "Start your second brain", className = "" }: { children?: ReactNode; className?: string }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [saved, setSaved] = useState(false);
  const [note, setNote] = useState("");
  const id = useId();
  return <><button className={`${s.primary} ${className}`} onClick={() => dialog.current?.showModal()}>{children}<ArrowUpRight size={17} aria-hidden="true" /></button><dialog ref={dialog} className={s.dialog} aria-labelledby={`${id}-title`}><div className={s.dialogTop}><span>YOUR FIRST THOUGHT</span><button className={s.iconButton} aria-label="Close note demo" onClick={() => dialog.current?.close()}><X size={20} /></button></div><h2 id={`${id}-title`}>Give an idea a home.</h2><p>This is a local demo. Write something you want to come back to.</p><form onSubmit={e => { e.preventDefault(); if (note.trim()) setSaved(true); }}><label htmlFor={`${id}-note`}>Your note</label><textarea id={`${id}-note`} required value={note} onChange={e => { setNote(e.target.value); setSaved(false); }} placeholder="A thought, a question, a small beginning…" /><button className={s.primary} type="submit">Save this thought <Check size={16} /></button><p className={s.status} role="status">{saved ? "Saved in this demo. Your next idea can start here, too." : "Your note stays in this page until you leave."}</p></form></dialog></>;
}

function Header({ name, logo = "leaf", tone = "" }: { name: string; logo?: string; tone?: string }) {
  const [open, setOpen] = useState(false);
  return <header className={`${s.header} ${tone}`}><a href="#top" className={s.wordmark} aria-label={`${name} home`}>{logo === "leaf" ? <Leaf size={23} aria-hidden="true" /> : logo === "network" ? <Network size={23} aria-hidden="true" /> : logo === "layers" ? <Layers size={23} aria-hidden="true" /> : <span className={s.brandMark} aria-hidden="true">{logo}</span>}{name}</a><button className={s.mobileMenu} aria-label={open ? "Close navigation" : "Open navigation"} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button><nav className={`${s.nav} ${open ? s.navOpen : ""}`} aria-label="Main navigation"><a href="#how" onClick={() => setOpen(false)}>How it works</a><a href="#inside" onClick={() => setOpen(false)}>Explore the space</a><Start>Start writing</Start></nav></header>;
}

const exampleNotes = [
  { title: "Make room for good ideas", tag: "Thinking", body: "The best ideas rarely arrive fully formed. They start as a question on a walk, a line in a book, a conversation that stays with you.", extra: "Keep the fragments. The connections will follow.", links: ["A slower morning", "Creative practice"] },
  { title: "A slower morning", tag: "Daily notes", body: "Coffee before notifications. Ten quiet minutes to write down what matters today. A little space between noticing and doing.", extra: "A small ritual can change the shape of a day.", links: ["Make room for good ideas", "Attention is a practice"] },
  { title: "Creative practice", tag: "Projects", body: "Collect what catches your attention. Read outside your usual field. Let two unrelated ideas sit next to each other.", extra: "Something new often starts with something you already know.", links: ["Make room for good ideas", "Reading list"] },
];

function Notebook({ compact = false }: { compact?: boolean }) {
  const [active, setActive] = useState(0);
  const [query, setQuery] = useState("");
  const note = exampleNotes[active];
  const filtered = exampleNotes.map((item, index) => ({ ...item, index })).filter(item => item.title.toLowerCase().includes(query.toLowerCase()));
  return <div className={`${s.notebook} ${compact ? s.compactBook : ""}`}><aside className={s.bookSidebar}><div className={s.workspace}><span className={s.avatar}>J</span>Jamie’s space</div><label className={s.searchLabel}><Search size={15} aria-hidden="true" /><span className={s.srOnly}>Search example notes</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Find a thought…" /></label><div className={s.sidebarCaption}>YOUR LIBRARY</div><div className={s.noteList}>{filtered.map(item => <button key={item.index} onClick={() => setActive(item.index)} aria-pressed={active === item.index}><FileText size={15} aria-hidden="true" />{item.title}</button>)}{!filtered.length && <p role="status" className={s.empty}>No notes found. Try “morning”.</p>}</div><div className={s.sidebarBottom}><Network size={15} /> Everything is connected</div></aside><article className={s.bookPage} aria-live="polite"><div className={s.documentBar}><span>Notes / {note.tag}</span><span><Check size={12} /> Saved</span></div><p className={s.noteDate}>THURSDAY, OCTOBER 2</p><h2>{note.title}</h2><p>{note.body}</p><blockquote>{note.extra}</blockquote><div className={s.relatedLabel}><Link2 size={14} /> CONNECTED THOUGHTS</div><div className={s.relatedNotes}>{note.links.map(link => <span key={link}>{link}<ArrowUpRight size={13} /></span>)}</div></article></div>;
}

function Footer({ name }: { name: string }) { return <footer className={s.footer}><span>{name} · A little more space to think.</span><span>Keep your thoughts. Find your next one.</span></footer>; }

export function PageOne() {
  return <div className={`${s.page} ${s.grove}`} id="top"><a className={s.skip} href="#content">Skip to content</a><div className={s.wrap}><Header name="grove" /><main id="content"><section className={s.groveHero}><div className={s.groveCopy}><p className={s.eyebrow}><span className={s.smallDot} /> A QUIETER PLACE FOR YOUR MIND</p><h1>Good thoughts<br />deserve a place<br />to <em>grow.</em></h1><p className={s.lead}>The note you scribbled. The article you loved. The idea you can’t quite explain. Bring them together in your second brain.</p><Start>Plant your first idea</Start><p className={s.ctaHint}>Less organizing. More understanding.</p></div><div className={s.groveVisual}><div className={s.groveVisualHead}><span>YOUR MIND, WITH A LITTLE MORE ROOM</span><Leaf size={18} /></div><div className={s.gardenIllustration} aria-hidden="true"><div className={s.stem} /><span className={s.leafOne} /><span className={s.leafTwo} /><span className={s.leafThree} /><span className={s.leafFour} /><div className={s.gardenLabel}>Curiosity is a good place to start.</div></div><div className={s.paperSlip}><span><Bookmark size={14} /> FIELD NOTE NO. 014</span><p>“What if I followed<br />this thought a little further?”</p><div>ideas / a beginning <ArrowUpRight size={16} /></div></div><div className={s.visualFoot}><span>One thought today.</span><span>A whole world tomorrow.</span></div></div></section><section className={s.groveSteps} id="how"><div><span>01 / CAPTURE</span><h2>Catch the little things.</h2><p>A thought, a link, a moment. Save it before it slips away.</p></div><div><span>02 / CONNECT</span><h2>Follow the thread.</h2><p>Link notes together and notice what keeps coming back.</p></div><div><span>03 / RETURN</span><h2>Find your way back.</h2><p>Your past thinking, ready when your next idea needs it.</p></div></section><section className={s.productSection} id="inside"><div className={s.sectionHeading}><div><p className={s.eyebrow}>A SPACE THAT FEELS LIKE YOURS</p><h2>Not another inbox.<br />A growing body of thought.</h2></div><p>Open a note. Follow a connection.<br />See where your curiosity takes you.</p></div><Notebook /></section></main><Footer name="grove" /></div></div>;
}

function Constellation() {
  const [selected, setSelected] = useState(0);
  const thoughts = ["The next big idea", "A conversation", "Something I read", "A passing thought", "A project in motion"];
  return <div className={s.constellation}><svg viewBox="0 0 660 430" className={s.graphLines} aria-hidden="true"><path d="M330 210 L110 90 M330 210 L545 85 M330 210 L110 335 M330 210 L545 340 M110 90 L110 335 M545 85 L545 340 M110 90 L545 85 M110 335 L545 340" /></svg>{thoughts.map((thought, i) => <button key={thought} className={`${s.graphNode} ${s[`node${i}`]} ${selected === i ? s.selectedNode : ""}`} onClick={() => setSelected(i)} aria-pressed={selected === i}>{i === 0 ? <Network size={22} aria-hidden="true" /> : <FileText size={16} aria-hidden="true" />}<span>{thought}</span><small>{i === 0 ? "12 connections" : ["", "A note from Tuesday", "Reading / 4 min", "Captured just now", "Ideas / in progress"][i]}</small></button>)}<div className={s.graphStatus} role="status"><span className={s.smallDot} /> Selected: {thoughts[selected]}</div></div>;
}

export function PageTwo() {
  return <div className={`${s.page} ${s.thread}`} id="top"><a className={s.skip} href="#content">Skip to content</a><div className={s.wrap}><Header name="thread" logo="network" /><main id="content"><section className={s.threadHero}><div className={s.threadTopline}><span>NOTES ARE JUST THE BEGINNING</span><span>PRIVATE THINKING. BIG POSSIBILITIES.</span></div><h1>Every idea has<br />a <em>next idea.</em></h1><div className={s.threadIntro}><p>A second brain for connecting what you know<br />with what you haven’t thought of yet.</p><Start>Find your thread</Start></div><Constellation /></section><section className={s.threadManifesto} id="how"><p className={s.eyebrow}>THINK BEYOND THE FOLDER</p><h2>Your thinking isn’t linear.<br />Your notes shouldn’t be either.</h2><div className={s.threadRows}><div><span>01</span><h3>Capture without friction</h3><p>Give every thought a place, before you know where it belongs.</p><Plus size={20} /></div><div><span>02</span><h3>Make unexpected connections</h3><p>Turn isolated notes into a network you can explore.</p><Link2 size={20} /></div><div><span>03</span><h3>Pick up where your mind left off</h3><p>Find the right fragment and move the idea forward.</p><MoveUpRight size={20} /></div></div></section><section className={s.productSection} id="inside"><div className={s.sectionHeading}><h2>A thought becomes<br />a trail.</h2><p>Click through this little corner of a second brain.</p></div><Notebook /></section></main><Footer name="thread" /></div></div>;
}

function DailyNote() {
  const [text, setText] = useState("Take the long way home. There might be something worth noticing.");
  const [saved, setSaved] = useState(false);
  const id = useId();
  return <div className={s.dailyNote}><div className={s.noteBinding} aria-hidden="true">{Array.from({ length: 6 }, (_, i) => <span key={i} />)}</div><div className={s.dailyPaper}><div className={s.dailyDate}><span>02 OCTOBER</span><span>THURSDAY</span></div><h2>A note to myself</h2><p>Small observations make a bigger picture.</p><label htmlFor={`${id}-daily`}>What’s on your mind?</label><textarea id={`${id}-daily`} value={text} onChange={e => { setText(e.target.value); setSaved(false); }} /><button onClick={() => setSaved(Boolean(text.trim()))}>Keep this thought <CornerDownLeft size={17} /></button><div role="status" className={s.dailyStatus}>{saved ? "✓ Thought saved in this demo." : "A thought doesn’t need to be finished to be worth keeping."}</div><div className={s.marginAnnotation}>start anywhere.</div></div></div>;
}

export function PageThree() {
  return <div className={`${s.page} ${s.margin}`} id="top"><a className={s.skip} href="#content">Skip to content</a><div className={s.wrap}><Header name="margin" logo="m." /><main id="content"><section className={s.marginHero}><div className={s.marginCopy}><p className={s.eyebrow}>FOR THE THOUGHTS BETWEEN EVERYTHING ELSE</p><h1>You don’t have<br />to hold it <em>all.</em></h1><p className={s.lead}>A home for the things on your mind.<br />Write them down. Let them connect.<br />Make room for what comes next.</p><Start>Make a little room</Start><div className={s.marginDetail}><span>NO PERFECT SYSTEM REQUIRED.</span><span>JUST YOU, AND A FIRST NOTE.</span></div></div><DailyNote /></section><section className={s.marginLetter} id="how"><span className={s.letterNumber}>A NOTE ON TAKING NOTES</span><h2>Not everything needs<br />to become a to-do.</h2><div><p>Some things are simply worth remembering. A sentence. An unfinished idea. The way you see the world today.</p><p>Margin gives these little things room to sit together. Over time, they become something you can return to: your own collection of understanding.</p><span className={s.handwriting}>Less in your head. More on the page.</span></div></section><section className={s.productSection} id="inside"><div className={s.sectionHeading}><h2>A place for<br />your kind of thinking.</h2><p>Try the notes below.<br />There’s no right order.</p></div><Notebook /></section></main><Footer name="margin" /></div></div>;
}

function SearchPreview() {
  const [query, setQuery] = useState("creative");
  const id = useId();
  const items = [{ title: "Creative practice", kind: "NOTE", text: "Keep an idea notebook. Make connections across fields.", count: "6 linked notes" }, { title: "Building a daily practice", kind: "JOURNAL", text: "A little creative work, every day. Even ten minutes counts.", count: "3 linked notes" }, { title: "The art of paying attention", kind: "BOOKMARK", text: "Creative work starts with noticing what others pass by.", count: "2 linked notes" }];
  const results = items.filter(item => `${item.title} ${item.text}`.toLowerCase().includes(query.toLowerCase()));
  return <div className={s.searchPreview}><div className={s.searchPreviewTop}><span><Command size={16} /> INDEX / YOUR KNOWLEDGE</span><span>SEARCH VIEW</span></div><label htmlFor={`${id}-search`}>What are you thinking about?</label><div className={s.largeSearch}><Search size={21} /><input id={`${id}-search`} value={query} onChange={e => setQuery(e.target.value)} /><kbd>↵</kbd></div><div className={s.resultCount} role="status">{results.length} results in your example library</div><div className={s.searchResults}>{results.map(item => <article key={item.title}><span className={s.resultKind}>{item.kind}</span><h3>{item.title}<ArrowUpRight size={18} /></h3><p>{item.text}</p><span className={s.resultLinks}><Link2 size={13} />{item.count}</span></article>)}{!results.length && <p>No matching thoughts. Try “creative” or “daily”.</p>}</div><div className={s.searchPreviewFoot}>Search the idea. Find the context.</div></div>;
}

export function PageFour() {
  return <div className={`${s.page} ${s.index}`} id="top"><a className={s.skip} href="#content">Skip to content</a><div className={s.wrap}><Header name="index" logo="+" /><main id="content"><section className={s.indexHero}><div className={s.indexCopy}><p className={s.eyebrow}>A PERSONAL KNOWLEDGE SYSTEM</p><h1>Your mind.<br />Well indexed.</h1><p className={s.lead}>Turn scattered notes into knowledge you can use. Capture, connect, and retrieve the right idea at the right moment.</p><Start>Build your index</Start><a className={s.textLink} href="#inside">Explore an example library <ArrowRight size={15} /></a><div className={s.indexMeta}><span><FileText size={15} /> Notes with context</span><span><Network size={15} /> Connected by you</span></div></div><SearchPreview /></section><section className={s.indexPrinciples} id="how"><div className={s.indexPrinciplesTitle}><span>SYSTEM OVER NOISE</span><h2>A reliable extension<br />of your thinking.</h2></div><div><span>01 — INPUT</span><h3>Capture the useful bits</h3><p>Bring notes, links, and questions into one searchable place.</p></div><div><span>02 — CONTEXT</span><h3>Connect the dots</h3><p>Link related thoughts so the context stays with the content.</p></div><div><span>03 — OUTPUT</span><h3>Put knowledge to work</h3><p>Retrieve what you need and turn past thinking into your next move.</p></div></section><section className={s.productSection} id="inside"><div className={s.sectionHeading}><h2>Structure that leaves<br />room for thought.</h2><p>A small example library.<br />Search a note to get started.</p></div><Notebook /></section></main><Footer name="index" /></div></div>;
}

function IdeaBoard() {
  const [active, setActive] = useState("Make something");
  const cards = [{ name: "Make something", text: "What if the first version was just for fun?", category: "A SMALL BEGINNING", icon: <Plus size={22} /> }, { name: "Keep looking", text: "There’s a whole idea hiding in that little detail.", category: "THINGS I NOTICED", icon: <Search size={22} /> }, { name: "Join the dots", text: "The book I read + that conversation yesterday.", category: "AN UNEXPECTED CONNECTION", icon: <Network size={22} /> }];
  return <div className={s.ideaBoard}><div className={s.boardTop}><span><Circle size={12} /> MY LITTLE UNIVERSE</span><span>3 IDEAS, AND COUNTING</span></div><div className={s.boardCards}>{cards.map((card, i) => <button key={card.name} className={`${s.ideaCard} ${s[`idea${i}`]} ${active === card.name ? s.ideaSelected : ""}`} onClick={() => setActive(card.name)} aria-pressed={active === card.name}><span className={s.ideaCategory}>{card.category}{card.icon}</span><strong>{card.name}</strong><p>{card.text}</p><span className={s.ideaBottom}>a thought worth keeping <ArrowUpRight size={16} /></span></button>)}</div><div className={s.boardFooter} role="status"><span><Link2 size={16} />{active} → Your next idea</span><span>Everything starts somewhere.</span></div></div>;
}

export function PageFive() {
  return <div className={`${s.page} ${s.commonplace}`} id="top"><a className={s.skip} href="#content">Skip to content</a><div className={s.wrap}><Header name="commonplace" logo="layers" /><main id="content"><section className={s.commonHero}><div className={s.commonEyebrow}><span>FOR CURIOUS MINDS & UNFINISHED IDEAS</span><span>EST. IN YOUR HEAD</span></div><div className={s.commonHeroText}><h1>A home for your<br /><em>beautiful mess.</em></h1><div><p>All those tabs, thoughts, and “I should remember this” moments. Give them somewhere to meet.</p><Start>Bring your brain along</Start><p className={s.ctaHint}>Start with one idea. See what happens.</p></div></div><IdeaBoard /></section><section className={s.commonHow} id="how"><h2>Collect first.<br />Make sense later.</h2><div className={s.commonHowItems}><div><span>01</span><h3>Drop it here.</h3><p>Notes, links, little sparks. No elaborate filing system needed.</p></div><div><span>02</span><h3>Mix things up.</h3><p>Put ideas next to each other. Notice the unexpected overlaps.</p></div><div><span>03</span><h3>Come back curious.</h3><p>Pick up an old thought. Make something new from it.</p></div></div></section><section className={s.productSection} id="inside"><div className={s.sectionHeading}><h2>Meet your mind<br />on a good day.</h2><p>Try this tiny collection.<br />Click a thought, follow a connection.</p></div><Notebook /></section></main><Footer name="commonplace" /></div></div>;
}
