"use client";

import { useState, type CSSProperties } from "react";
import { ArrowRight, ArrowLeft, FileText, Link2, Compass, Search, Bookmark, Check, Plus, Mountain, Layers } from "lucide-react";
import s from "./Designs.module.css";

const observations = [
  { title: "Reading", line: "Attention is a practice, not a resource.", text: "The more I notice, the more there is to notice. Attention seems less like a finite thing and more like a skill I return to, again and again.", tag: "attention" },
  { title: "Morning", line: "Leave the first hour open.", text: "A quieter start changes the tone of the day. Before inputs, before demands, give myself time to think, read, and notice what is here.", tag: "routine" },
  { title: "Project", line: "Make space before making plans.", text: "Clarify what I am paying attention to before I start mapping next steps. A short pause now leads to better direction later.", tag: "planning" },
];
const atlasNotes = [
  { title: "A line worth keeping", text: "Small, consistent acts compound into a different you." },
  { title: "Reading: attention", text: "Attention is a kind of care." },
  { title: "Project: a slower morning", text: "Leave the first hour open. Notice what returns." },
  { title: "An idea for Monday", text: "What would be simpler if it were easier?" },
];

function Action({ children, href = "#demo" }: { children: React.ReactNode; href?: string }) { return <a className={s.action} href={href}>{children}<ArrowRight size={20} aria-hidden /></a>; }
function End({ name, title, copy }: { name: string; title: string; copy: string }) { return <section className={s.close} id="close"><h2>{title}</h2><p>{copy}</p><Action>Try the interactive notebook</Action><footer><span>{name}</span><span>A fictional note-taking product · Interactive concept</span><a href="#top">Back to the beginning ↑</a></footer></section>; }

export function PageOne() {
  const [selected, select] = useState(2);
  return <main className={`${s.page} ${s.atlas}`} id="top">
    <div className={s.atlasSky}>
      <header className={s.header}><a href="#top" className={s.brand}><Mountain size={31} />Waypoint</a><nav aria-label="Page navigation"><a href="#how">Capture</a><a href="#demo">Connect</a><a href="#close">Find</a></nav><a className={s.outlineAction} href="#demo">Open your atlas</a></header>
      <section className={s.atlasHero}><div className={s.atlasOffer}><h1>Find your way<br />back to a<br />good idea.</h1><p>A home for the notes, references,<br className={s.desktopBreak} /> and connections you want to keep.</p><Action>Explore the demo</Action><p className={s.mapMotto}>Different thoughts.<br />A clearer path.</p></div>
        <div className={s.atlasMap} id="demo" aria-label="Interactive illustrative note atlas"><span className={s.demoLabel}>Illustrative notes · Select a destination</span><svg viewBox="0 0 900 620" className={s.routeLines} aria-hidden><path d="M190 135 C480 50 455 230 640 210 S850 450 680 520 S490 360 390 360 S160 420 190 135" /><path d="M190 135 C270 190 170 350 390 360" className={s.secondaryRoute} /></svg>
          {atlasNotes.map((n,i)=><button key={n.title} className={`${s.mapNote} ${s[`destination${i}`]} ${selected===i?s.activeDestination:""}`} onClick={()=>select(i)} aria-pressed={selected===i}><strong>{n.title}</strong><small>Illustrative note</small><span>“{n.text}”</span><i aria-hidden /></button>)}
          <div className={s.mapLegend}><Compass size={21} /><span aria-live="polite">{atlasNotes[selected].title}</span><span>Follow your curiosity</span></div>
        </div>
      </section>
    </div>
    <section className={s.atlasSteps} id="how">{[[FileText,"Capture a thought","Jot down ideas, notes, links, and more before they slip away."],[Link2,"Connect the context","Link related notes and see the bigger picture take shape."],[Compass,"Return when it matters","Find what you need and pick up right where you left off."]].map(([Icon,title,copy],i)=>{const Glyph=Icon as typeof FileText;return <article key={i}><Glyph size={27}/><div><h2>{title as string}</h2><p>{copy as string}</p></div></article>;})}</section>
    <End name="Waypoint" title="Ideas have places, too." copy="A note is a beginning. Give it a path back into your life." />
  </main>;
}

export function PageTwo() {
  const [query,setQuery]=useState(""); const [active,setActive]=useState(-1);
  const visible=observations.filter((n,i)=>(active<0||active===i)&&`${n.title} ${n.line} ${n.text}`.toLowerCase().includes(query.toLowerCase()));
  return <main className={`${s.page} ${s.field}`} id="top">
    <header className={s.header}><a href="#top" className={s.brand}>FIELDNOTES</a><nav aria-label="Page navigation"><a href="#demo">Notes</a><a href="#field-index">Index</a><a href="#how">Field guide</a></nav><Action>Open the field book</Action></header>
    <section className={s.fieldOffer}><h1>Keep what catches<br />your attention.</h1><div><p>Small observations.<br />Useful connections.<br />A place to think again.</p><Action>Open the field book</Action></div></section>
    <section className={s.ledger} id="demo" aria-label="Illustrative observation ledger">
      <aside className={s.ledgerIndex}><h2>FIELDNOTES</h2><button className={active<0?s.selectedIndex:""} onClick={()=>setActive(-1)}><FileText size={17}/>All Notes<span>3</span></button>{observations.map((n,i)=><button key={n.title} className={active===i?s.selectedIndex:""} onClick={()=>setActive(i)}><Bookmark size={17}/>{n.title}<span>1</span></button>)}<label className={s.search}><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search notes…" aria-label="Search illustrative observations"/></label><p>Same curiosity.<br />A clearer tomorrow.</p></aside>
      <div className={s.observationList}><div className={s.ledgerHeading}><h2>All Notes</h2><small>Illustrative notes</small></div>{visible.length?visible.map(n=><article key={n.title}><time>APR 12<br/>FIELD BOOK</time><div><span className={s.tag}>{n.title}</span><h3>{n.line}</h3><p>{n.text}</p><small>#{n.tag}　#notes　#practice</small></div></article>):<p className={s.empty}>No observation matches “{query}”. Try another word or select All Notes.</p>}</div>
      <aside className={s.ledgerConnections} id="field-index"><h2>Index</h2><div className={s.fieldConnections}><div>Reading<br/><strong>Attention is a practice,<br/>not a resource.</strong></div><svg viewBox="0 0 260 110" aria-hidden><path d="M130 0 L35 100 M130 0 L225 100"/></svg><div className={s.connectionPair}><span>Morning<br/>Leave the first<br/>hour open.</span><span>Project<br/>Make space before<br/>making plans.</span></div></div><h3>Related ideas</h3><p><FileText size={15}/>Focus creates options.</p><p><FileText size={15}/>A calmer start.</p><p><FileText size={15}/>Better questions, better work.</p><a href="#field-index">Explore the index <ArrowRight size={16}/></a></aside>
    </section>
    <section className={s.fieldGuide} id="how"><h2>Notice. Record.<br/>Return.</h2><p>A passing observation can become the beginning of something. Keep its words, add its context, and follow it somewhere useful.</p><div><span>CAPTURE</span><span>CONNECT</span><span>REVISIT</span></div></section>
    <End name="FIELDNOTES" title="A quieter kind of work." copy="Capture what matters, see how it fits, and return when it is useful."/>
  </main>;
}

const passes=[{name:"Capture",title:"A slower morning",text:"Woke up without an alarm today. Made coffee, sat by the window, and noticed how different everything feels when I give myself a little more time."},{name:"Context",title:"Attention is a kind of care",text:"Where I place my attention shapes my day. A more intentional morning helps me show up better for the people and things I care about."},{name:"Connection",title:"Make room for what matters",text:"A slower morning is a practical way to live in line with my values. When I protect my attention early, I have more of it for what matters."}];
export function PageThree(){const [alignment,setAlignment]=useState(35);return <main className={`${s.page} ${s.overprint}`} id="top"><header className={s.header}><a href="#top" className={s.brand}><span>OVER</span><span>PRINT</span></a><nav aria-label="Page navigation"><a href="#demo">Notes</a><a href="#how">Approach</a><a href="#close">Explore</a></nav><a className={s.outlineAction} href="#demo">Make a connection</a></header>
    <section className={s.overprintHero}><div className={s.printOffer}><h1><span>Your thoughts.</span><br/><em>In</em> <b>good</b> <i>company.</i></h1><p>Capture an idea. Add its context.<br/>See what comes together.</p><Action>Make a connection</Action></div><div className={s.printDemo} id="demo"><span className={s.demoLabel}>Illustrative notes</span><div className={s.passStack}>{passes.map((p,i)=><article key={p.name} className={`${s.pass} ${s[`pass${i}`]}`} style={{"--pass-shift":`${(alignment-100)*(i-1)*.38}px`} as CSSProperties}><h2>{p.name}</h2><h3>{p.title}</h3><p>{p.text}</p><small>#{i===0?"routine":i===1?"attention":"intention"}</small></article>)}</div><label className={s.registrationControl}><span>Bring the thoughts into register</span><input type="range" min="0" max="100" value={alignment} onChange={e=>setAlignment(Number(e.target.value))} aria-label="Align the illustrative note passes"/><button onClick={()=>setAlignment(100)}><Layers size={16}/>{alignment===100?"In register":"Align the notes"}</button></label></div></section>
    <section className={s.printSteps} id="how"><h2>Three passes.<br/>Richer thinking.</h2>{passes.map((p,i)=><article key={p.name} className={s[`printStep${i}`]}><span>{i+1}</span><h3>{p.name}</h3><p>{["Write the idea in your own words. Get it out of your head and into a lasting place.","Add background, related ideas, people, places, or questions. Give it depth.","See new meaning as your notes overlap. Turn separate thoughts into something bigger."][i]}</p></article>)}</section><End name="OVERPRINT" title="Same thought. A wider frame." copy="Your notes do not have to stay separate. Make room for what comes together."/></main>;}

const catalog=[
  ["A1","Attention","Where your attention goes, your life arranges itself. Not a slogan — a reminder."], ["B3","Walking","Ten minutes outside clears the static. Ideas arrive in motion."], ["C2","A sentence to keep","A kinder routine is a form of self-respect. Worth returning to."], ["D4","Reading list","A page about listening. A chapter about gardens. A book to revisit."], ["E1","Monday idea","What if friction is a signal, not a problem?"], ["F3","Window light","The desk looks different in afternoon light. Softer thoughts today."], ["G2","Morning pages","Stillness on paper. Three pages, no editing."], ["H4","Make room","Clear a little space today. Less in. More available."], ["I1","Work in progress","A slower, truer version. Iteration is a kind of care."], ["J3","A question","What am I avoiding right now? Be honest."], ["K2","Garden notes","First seedlings up. Patience is its own harvest."], ["L4","Listen again","That conversation at 37:12. A useful way to think about time."]
];
export function PageFour(){const [selected,setSelected]=useState(0);const [query,setQuery]=useState(""); const found=catalog.map((n,i)=>({n,i})).filter(({n})=>n.join(" ").toLowerCase().includes(query.toLowerCase()));return <main className={`${s.page} ${s.commonplace}`} id="top"><header className={s.header}><a href="#top" className={s.brand}>COMMONPLACE</a><nav aria-label="Page navigation"><a href="#demo">Notebook</a><a href="#knowledge-map">Map</a><a href="#close">About</a></nav><label className={s.search}><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search notes…" aria-label="Search illustrative catalog"/></label></header>
    <section className={s.catalogHero}><div className={s.catalogOffer}><h1>A place for<br/>every passing<br/>thought.</h1><p>Collect your notes.<br/>Mark the ones that matter.<br/>Find your own path<br/>through them.</p><Action>Browse your notebook</Action></div><div className={s.catalogDemo} id="demo"><div className={s.catalogHeading}><span>Illustrative notes</span><span>Select a cell to follow its context</span></div><div className={s.catalogCells}>{found.map(({n,i})=><button key={n[0]} aria-pressed={selected===i} onClick={()=>setSelected(i)} className={selected===i?s.selectedCell:""}><small>{n[0]}<i aria-hidden/></small><strong>{n[1]}</strong><p>{n[2]}</p></button>)}{!found.length&&<p className={s.empty}>No matching notes. Try another word.</p>}</div></div><aside className={s.knowledgeMap} id="knowledge-map"><h2>Knowledge map</h2><svg viewBox="0 0 250 400" aria-hidden><path d="M40 40 C50 130 110 190 145 190 S240 120 205 100 M145 190 C120 270 10 250 25 290 M145 190 C165 275 190 330 190 365"/><circle cx="40" cy="40" r="6"/><circle cx="205" cy="100" r="6"/><circle cx="145" cy="190" r="9"/><circle cx="25" cy="290" r="6"/><circle cx="190" cy="365" r="6"/></svg><span className={s.mapCode1}>{catalog[(selected+2)%12][0]}<br/>{catalog[(selected+2)%12][1]}</span><span className={s.mapCode2}>{catalog[(selected+1)%12][0]}<br/>{catalog[(selected+1)%12][1]}</span><span className={s.mapCode3} aria-live="polite"><b>{catalog[selected][0]}</b><br/>{catalog[selected][1]}</span><span className={s.mapCode4}>{catalog[(selected+4)%12][0]}<br/>{catalog[(selected+4)%12][1]}</span><p>Ideas connect.<br/>You decide the path.</p></aside></section>
    <section className={s.catalogContext} id="how"><div><h2>Your thoughts,<br/>in context.</h2><p>Notes are more useful when they can find each other. Follow curiosity through your own collection.</p></div><article aria-live="polite"><small>{catalog[selected][0]} · Selected note</small><h3>{catalog[selected][1]}</h3><p>{catalog[selected][2]}</p><span><Link2 size={17}/>Linked to {catalog[(selected+1)%12][1]}</span></article></section><End name="COMMONPLACE" title="Different thoughts. A larger picture." copy="Build a collection you can keep finding your way through."/></main>;}

const keeperNotes=[{title:"A thought on attention",text:"Attention isn’t a fixed amount. It’s a practice — a series of small returns. The tools we use should reduce friction, not add noise. A calmer space helps me hear what’s actually mine."},{title:"Leave room for a slower morning",text:"Mornings don’t need to be optimized. A slower start often leads to a clearer mind. Try a thirty-minute buffer — no email, no news, just a bit of space."},{title:"What if this was simpler?",text:"Complexity often hides a lack of conviction. What would this look like in half the steps? Keep the useful part. Let the rest wait."},{title:"Reading worth returning to",text:"Good books don’t end. They wait. Keep the sentence that changed something, and leave yourself a way back to it."}];
export function PageFive(){const [selected,setSelected]=useState(0);const [kept,setKept]=useState<number[]>([]);const [deferred,setDeferred]=useState<number[]>([1,3]);const keep=()=>setKept(old=>old.includes(selected)?old.filter(i=>i!==selected):[...old,selected]);return <main className={`${s.page} ${s.keeper}`} id="top"><section className={s.keeperHero}><div className={s.keeperOffer}><a className={s.brand} href="#top">KEEPER</a><h1>Keep the thought.<br/>Find the thread.</h1><p>A working bench for your notes, fragments, and unfinished ideas.</p><Action>Start collecting</Action><small>Same thoughts.<br/>A clearer tomorrow.</small></div><div className={s.workbench}><nav aria-label="Page navigation"><a href="#demo">Notes</a><a href="#collection">Collection</a><a href="#set-aside">Set aside</a><a href="#close">About</a></nav><span className={s.demoLabel}>Illustrative notes</span><div className={s.noteRail} id="demo"><button className={s.railArrow} aria-label="Previous note" onClick={()=>setSelected((selected+3)%4)}><ArrowLeft size={18}/></button>{keeperNotes.map((n,i)=><button key={n.title} className={`${s.railNote} ${selected===i?s.selectedRail:""}`} onClick={()=>setSelected(i)} aria-pressed={selected===i}><strong>{n.title}</strong><small>FIELD NOTE · APR {12-i*2}</small>{selected===i&&<Bookmark size={20} aria-hidden/>}</button>)}<button className={s.railArrow} aria-label="Next note" onClick={()=>setSelected((selected+1)%4)}><ArrowRight size={18}/></button></div>
      <article className={s.keeperReading}><div><h2>{keeperNotes[selected].title}</h2><button onClick={keep}>{kept.includes(selected)?<Check size={17}/>:<Bookmark size={17}/>} {kept.includes(selected)?"Kept":"Keep"}</button></div><small>APR {12-selected*2} · PERSONAL NOTE</small><p>{keeperNotes[selected].text}</p><div className={s.keeperTags}><span>#attention</span><span>#tools</span><span>#mindset</span><button onClick={()=>setDeferred(old=>old.includes(selected)?old.filter(i=>i!==selected):[...old,selected])}>{deferred.includes(selected)?"Return to the rail":"Set aside"}<Plus size={15}/></button></div></article>
      <div id="set-aside" className={s.setAside}><h3>Set aside · Still within reach</h3><div>{deferred.map(i=><button key={i} onClick={()=>setSelected(i)}>{keeperNotes[i].title}<small>Return to this thought <ArrowRight size={14}/></small></button>)}{!deferred.length&&<p>Nothing set aside. Your thoughts are all on the rail.</p>}</div></div></div></section>
      <section className={s.collection} id="collection"><div><h2>Your collected thoughts</h2><p>A lighter mind, one note at a time.</p><span aria-live="polite">{kept.length?`${kept.length} ${kept.length===1?"thought":"thoughts"} kept in this demo.`:"Select a note and keep it to build your collection."}</span></div><div>{(kept.length?kept:[0,1,2]).map(i=><button key={i} onClick={()=>{setSelected(i);document.getElementById("demo")?.scrollIntoView({behavior:"smooth",block:"center"});}}><span>{keeperNotes[i].title}</span><small>{kept.includes(i)?"Kept":"Illustrative note"}</small><ArrowRight size={18}/></button>)}</div></section><End name="KEEPER" title="Unfinished is still worth keeping." copy="Keep a thought, follow its thread, and return when you are ready."/></main>;}

