"use client";

import { useId, useRef, useState } from "react";
import s from "./Designs.module.css";

const examples = [
  { title: "A city at walking speed", tag: "Observation", body: "The best route is rarely the shortest. Leave room for the bookshop, the shaded street, the unexpected conversation.", related: "Make room for detours" },
  { title: "Make room for detours", tag: "Idea", body: "A little unplanned time gives an idea somewhere to land. Protect a blank space in the week.", related: "A city at walking speed" },
  { title: "Things worth returning to", tag: "Reading", body: "Keep the passage that changes how you see something. Add your own thought beside it, so the reason survives the bookmark.", related: "Make room for detours" },
];

function Demo({ mode = "default" }: { mode?: string }) {
  const id = useId();
  const [selected, setSelected] = useState(0);
  const [query, setQuery] = useState("");
  const [draft, setDraft] = useState("");
  const [notes, setNotes] = useState(examples);
  const [status, setStatus] = useState("");
  const [link, setLink] = useState(false);
  const shown = notes.filter(n => n.title.toLowerCase().includes(query.toLowerCase()));
  const active = notes[selected];
  return <section className={`${s.demo} ${mode === "wide" ? s.wideDemo : ""}`} aria-labelledby={`${id}-heading`}>
    <div className={s.demoTop}><span className={s.demoMark}>e.</span><h2 id={`${id}-heading`}>Your little universe</h2><span className={s.demoLabel}>Interactive example</span></div>
    <div className={s.workbench}>
      <aside className={s.noteList}><label htmlFor={`${id}-search`}>Find a thought</label><input id={`${id}-search`} type="search" placeholder="Search example notes" value={query} onChange={e => setQuery(e.target.value)} />
        <div className={s.noteCount}>{shown.length} {shown.length === 1 ? "note" : "notes"}</div>
        {shown.length ? shown.map(n => <button key={n.title} className={active.title === n.title ? s.activeNote : ""} aria-pressed={active.title === n.title} onClick={() => { setSelected(notes.indexOf(n)); setLink(false); }}><small>{n.tag}</small><span>{n.title}</span><span aria-hidden="true">↗</span></button>) : <p>No notes found. Try “city” or clear your search.</p>}
      </aside>
      <article className={s.noteBody}><span className={s.tag}>{active.tag}</span><h3>{active.title}</h3><p>{active.body}</p><div className={s.noteRule} /><button className={s.linkControl} aria-expanded={link} onClick={() => setLink(!link)}>{link ? "− Hide connection" : "+ Follow this thought"}</button>{link && <div className={s.connection}><small>Connected note</small><button onClick={() => { setSelected(notes.findIndex(n => n.title === active.related)); setLink(false); }}>{active.related} <span aria-hidden="true">→</span></button><p>Ideas become more useful when you can see what sits beside them.</p></div>}</article>
    </div>
    <form className={s.capture} onSubmit={e => { e.preventDefault(); const value = draft.trim(); if (!value) { setStatus("Write a thought before adding it."); return; } const title = value.length > 48 ? `${value.slice(0, 45)}…` : value; setNotes([...notes, { title, tag: "Your thought", body: value, related: examples[0].title }]); setSelected(notes.length); setDraft(""); setQuery(""); setLink(false); setStatus("Added to this example. Notes reset when you leave this page."); }}>
      <label htmlFor={`${id}-capture`}>Catch a thought before it goes</label><div><input id={`${id}-capture`} value={draft} onChange={e => setDraft(e.target.value)} placeholder="Something you want to remember…" maxLength={300} required /><button type="submit">Add note <span aria-hidden="true">↵</span></button></div><p role="status">{status || "Try searching, opening a connection, or adding your own note. This demo stays on this page."}</p>
    </form>
  </section>;
}

function Start({ label = "Make a little space", className = "" }: { label?: string; className?: string }) {
  const ref = useRef<HTMLDialogElement>(null);
  const id = useId();
  const [text, setText] = useState("");
  const [saved, setSaved] = useState(false);
  return <><button className={`${s.primary} ${className}`} onClick={() => { setSaved(false); ref.current?.showModal(); }}>{label} <span aria-hidden="true">↗</span></button><dialog ref={ref} className={s.dialog} aria-labelledby={`${id}-title`}><div className={s.dialogTop}><span>Elsewhere / a first thought</span><button autoFocus aria-label="Close first thought" onClick={() => ref.current?.close()}>×</button></div><h2 id={`${id}-title`}>What’s on your mind?</h2><p>Start with one thought. No account needed for this local example.</p><form onSubmit={e => { e.preventDefault(); setSaved(true); }}><label htmlFor={`${id}-text`}>Your first note</label><textarea id={`${id}-text`} required value={text} onChange={e => { setText(e.target.value); setSaved(false); }} placeholder="I’ve been thinking about…" /><button className={s.primary} type="submit">Keep this thought</button><p role="status">{saved ? "Kept in this open example. Nothing was sent or stored on a server." : "Your note lasts while this page is open."}</p></form></dialog></>;
}

function Header({ number }: { number: string }) { return <header className={s.header} data-design={number}><a className={s.brand} href="#home" aria-label="Elsewhere home"><span aria-hidden="true">✳</span> elsewhere</a><nav aria-label="Main navigation"><a href="#how">How it works</a><a href="#example">Try it</a><Start label="Start a note" /></nav></header>; }
function Footer() { return <footer className={s.footer}><a className={s.brand} href="#home">✳ elsewhere</a><span>A home for what’s on your mind.</span><a href="#example">Explore the example ↗</a></footer>; }
function Shell({ theme, children }: { theme: string; children: React.ReactNode }) { return <div id="home" className={`${s.root} ${s[theme]}`}><a className={s.skip} href="#main">Skip to content</a>{children}</div>; }

export function PageOne() { return <Shell theme="one"><Header number="one" /><main id="main"><section className={s.oneHero}><div className={s.oneCopy}><p className={s.eyebrow}>Notes, with somewhere to go.</p><h1>Your mind.<br /><span>A little more room.</span></h1><p className={s.lede}>For passing thoughts, deep dives, and the things you swear you’ll remember. Give them a home in Elsewhere.</p><Start /><a className={s.textLink} href="#example">Take a look inside ↓</a></div><div className={s.indexArt} aria-label="Illustrative index of connected thoughts"><span className={s.indexTitle}>THE THOUGHT INDEX</span><div className={s.indexRow}><span>01</span><b>A passing thought</b><span>↗</span></div><div className={s.indexRow}><span>02</span><b>A good question</b><span>↗</span></div><div className={s.indexRow}><span>03</span><b>The beginning of something</b><span>↗</span></div><div className={s.indexBottom}><span>Not everything needs<br />an answer. Just a place.</span><span className={s.largeStar} aria-hidden="true">✳</span></div></div></section><section id="how" className={s.oneSteps}><h2>A second brain.<br />Still entirely yours.</h2><div><p><b>Catch it.</b> Write the fragment while it’s fresh.</p><p><b>Connect it.</b> Put related ideas within reach.</p><p><b>Come back.</b> Find the thought when you need it.</p></div></section><div id="example" className={s.exampleSection}><Demo /></div></main><Footer /></Shell>; }

export function PageTwo() { return <Shell theme="two"><Header number="two" /><main id="main"><section className={s.twoHero}><p className={s.eyebrow}>A place to grow a thought</p><h1>Small notes.<br /><em>Unexpected beginnings.</em></h1><div className={s.twoIntro}><p className={s.lede}>A sentence from a book. A question on the train. An idea with no name yet. Elsewhere keeps the small things close, until they become something.</p><Start label="Plant your first thought" /></div><div className={s.garden} aria-label="Illustrative progression from a captured thought to a connected idea"><div><span>capture</span><i className={s.seed} /><p>“What if I walked<br />the long way home?”</p></div><div><span>connect</span><i className={s.sprout}>⌁</i><p>A note on attention.<br />A place on a map.</p></div><div><span>return</span><i className={s.flower}>✳</i><p>Something you didn’t<br />know you were looking for.</p></div></div></section><section id="how" className={s.gardenStory}><h2>No perfect system required.</h2><p>You don’t have to know where an idea belongs before you write it down. Begin with a note. Add a connection. Let the shape emerge as you return.</p></section><div id="example" className={s.exampleSection}><p className={s.eyebrow}>A few thoughts to wander through</p><Demo /></div></main><Footer /></Shell>; }

export function PageThree() { return <Shell theme="three"><Header number="three" /><main id="main"><section className={s.threeHero}><div><p className={s.eyebrow}>Keep the thought. Find the thread.</p><h1>Nothing good<br />starts in<br /><em>isolation.</em></h1><p className={s.lede}>Your ideas have things in common. Elsewhere gives your notes a place to meet—and you a way back to what matters.</p><Start label="Find your first thread" /></div><div className={s.constellation} aria-label="Illustrative connected notes"><svg viewBox="0 0 500 500" aria-hidden="true"><path d="M80 110L265 200L430 100M265 200L375 390L100 360L80 110M100 360L265 200" /></svg><div className={s.nodeA}><small>OBSERVATION</small><b>The long way home</b></div><div className={s.nodeB}><span aria-hidden="true">✳</span><b>Paying attention</b></div><div className={s.nodeC}><small>QUESTION</small><b>What did I miss?</b></div><div className={s.nodeD}><small>READING</small><b>On noticing</b></div><div className={s.nodeE}><small>IDEA</small><b>A field guide to everyday</b></div></div></section><section id="how" className={s.threadStory}><span aria-hidden="true">↳</span><h2>A notebook remembers.<br />A second brain connects.</h2><p>Collect the fragments. Link related notes. Follow a thread you’ve already started, instead of starting from scratch.</p></section><div id="example" className={s.exampleSection}><Demo mode="wide" /></div></main><Footer /></Shell>; }

export function PageFour() { return <Shell theme="four"><Header number="four" /><main id="main"><section className={s.fourHero}><p className={s.eyebrow}>An everyday tool for an untidy mind.</p><h1>PUT IT<br />SOMEWHERE.</h1><div className={s.fourBottom}><p className={s.lede}>Less “I had a thought.”<br />More “here it is.”<br />Notes, connections, and a way back.</p><Start label="Give a thought a home" /><span className={s.stamp} aria-hidden="true">OPEN<br />FOR IDEAS<br />↙</span></div></section><section id="how" className={s.toolInstructions}><h2>Three useful habits.<br />One place for all of them.</h2><ol><li><span>01 / CAPTURE</span><h3>Don’t hold it all in.</h3><p>Write the rough version. One sentence is enough.</p></li><li><span>02 / CONNECT</span><h3>Leave yourself a trail.</h3><p>Link the thought to something you already know.</p></li><li><span>03 / RETURN</span><h3>Pick up where you left off.</h3><p>Search for the words you remember, then follow the thread.</p></li></ol></section><div id="example" className={s.exampleSection}><div className={s.sectionIntro}><h2>Take it for a spin.</h2><p>Actual buttons. Example thoughts.<br />A small place to try the idea.</p></div><Demo mode="wide" /></div></main><Footer /></Shell>; }

export function PageFive() { return <Shell theme="five"><Header number="five" /><main id="main"><section className={s.fiveHero}><div className={s.fiveTitle}><p className={s.eyebrow}>For your inner world</p><h1>Some thoughts<br />deserve a<br /><em>second home.</em></h1><p className={s.lede}>A quiet place to collect what catches your attention. Keep your notes, trace their connections, and make room for the next idea.</p><Start label="Open your notebook" /></div><div className={s.collection}><div className={s.collectionTop}><span>Collected, not forgotten.</span><span aria-hidden="true">↙</span></div><div className={s.bookA}><span>FIELD NOTES</span><b>The art<br />of noticing</b><span aria-hidden="true">✳</span></div><div className={s.bookB}><span>LOOSE THOUGHTS</span><b>Maybe<br />there’s<br />something<br />here.</b><small>Keep the beginning.</small></div><div className={s.bookC}><span>READING ROOM</span><b>Words to<br />return to.</b><span aria-hidden="true">↗</span></div><p>Illustrative notebooks from an everyday mind.</p></div></section><section id="how" className={s.fiveStory}><h2>You don’t have to<br />make sense of it all.<br /><em>Just make a start.</em></h2><div><p>Catch the idea in your own words. Connect it to a passage, a question, another thought.</p><p>Then come back when you’re ready. Elsewhere is a place for unfinished thinking, too.</p></div></section><div id="example" className={s.exampleSection}><Demo /></div></main><Footer /></Shell>; }
